/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aaveInterfaceSol from "./AaveInterface.sol";
export type { aaveInterfaceSol };
import type * as cTokenInterfaceSol from "./CTokenInterface.sol";
export type { cTokenInterfaceSol };
import type * as cometInterfaceSol from "./CometInterface.sol";
export type { cometInterfaceSol };
export type { IERC20NonStandard } from "./IERC20NonStandard";
export type { IWETH9 } from "./IWETH9";
