/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace CometMigratorV2 {
  export type CompoundV2CollateralStruct = {
    cToken: PromiseOrValue<string>;
    amount: PromiseOrValue<BigNumberish>;
  };

  export type CompoundV2CollateralStructOutput = [string, BigNumber] & {
    cToken: string;
    amount: BigNumber;
  };

  export type CompoundV2BorrowStruct = {
    cToken: PromiseOrValue<string>;
    amount: PromiseOrValue<BigNumberish>;
  };

  export type CompoundV2BorrowStructOutput = [string, BigNumber] & {
    cToken: string;
    amount: BigNumber;
  };

  export type SwapStruct = {
    path: PromiseOrValue<BytesLike>;
    amountInMaximum: PromiseOrValue<BigNumberish>;
  };

  export type SwapStructOutput = [string, BigNumber] & {
    path: string;
    amountInMaximum: BigNumber;
  };

  export type CompoundV2PositionStruct = {
    collateral: CometMigratorV2.CompoundV2CollateralStruct[];
    borrows: CometMigratorV2.CompoundV2BorrowStruct[];
    swaps: CometMigratorV2.SwapStruct[];
  };

  export type CompoundV2PositionStructOutput = [
    CometMigratorV2.CompoundV2CollateralStructOutput[],
    CometMigratorV2.CompoundV2BorrowStructOutput[],
    CometMigratorV2.SwapStructOutput[]
  ] & {
    collateral: CometMigratorV2.CompoundV2CollateralStructOutput[];
    borrows: CometMigratorV2.CompoundV2BorrowStructOutput[];
    swaps: CometMigratorV2.SwapStructOutput[];
  };

  export type AaveV2CollateralStruct = {
    aToken: PromiseOrValue<string>;
    amount: PromiseOrValue<BigNumberish>;
  };

  export type AaveV2CollateralStructOutput = [string, BigNumber] & {
    aToken: string;
    amount: BigNumber;
  };

  export type AaveV2BorrowStruct = {
    aDebtToken: PromiseOrValue<string>;
    amount: PromiseOrValue<BigNumberish>;
  };

  export type AaveV2BorrowStructOutput = [string, BigNumber] & {
    aDebtToken: string;
    amount: BigNumber;
  };

  export type AaveV2PositionStruct = {
    collateral: CometMigratorV2.AaveV2CollateralStruct[];
    borrows: CometMigratorV2.AaveV2BorrowStruct[];
    swaps: CometMigratorV2.SwapStruct[];
  };

  export type AaveV2PositionStructOutput = [
    CometMigratorV2.AaveV2CollateralStructOutput[],
    CometMigratorV2.AaveV2BorrowStructOutput[],
    CometMigratorV2.SwapStructOutput[]
  ] & {
    collateral: CometMigratorV2.AaveV2CollateralStructOutput[];
    borrows: CometMigratorV2.AaveV2BorrowStructOutput[];
    swaps: CometMigratorV2.SwapStructOutput[];
  };
}

export interface CometMigratorV2Interface extends utils.Interface {
  functions: {
    "aaveV2LendingPool()": FunctionFragment;
    "baseToken()": FunctionFragment;
    "cETH()": FunctionFragment;
    "comet()": FunctionFragment;
    "inMigration()": FunctionFragment;
    "isUniswapLiquidityPoolToken0()": FunctionFragment;
    "migrate(((address,uint256)[],(address,uint256)[],(bytes,uint256)[]),((address,uint256)[],(address,uint256)[],(bytes,uint256)[]),uint256)": FunctionFragment;
    "swapRouter()": FunctionFragment;
    "sweep(address)": FunctionFragment;
    "sweepee()": FunctionFragment;
    "uniswapLiquidityPool()": FunctionFragment;
    "uniswapV3FlashCallback(uint256,uint256,bytes)": FunctionFragment;
    "weth()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "aaveV2LendingPool"
      | "baseToken"
      | "cETH"
      | "comet"
      | "inMigration"
      | "isUniswapLiquidityPoolToken0"
      | "migrate"
      | "swapRouter"
      | "sweep"
      | "sweepee"
      | "uniswapLiquidityPool"
      | "uniswapV3FlashCallback"
      | "weth"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "aaveV2LendingPool",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "baseToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "cETH", values?: undefined): string;
  encodeFunctionData(functionFragment: "comet", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "inMigration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isUniswapLiquidityPoolToken0",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "migrate",
    values: [
      CometMigratorV2.CompoundV2PositionStruct,
      CometMigratorV2.AaveV2PositionStruct,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sweep",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "sweepee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "uniswapLiquidityPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapV3FlashCallback",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(functionFragment: "weth", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "aaveV2LendingPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "baseToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cETH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "comet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "inMigration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isUniswapLiquidityPoolToken0",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "migrate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swapRouter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sweep", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sweepee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "uniswapLiquidityPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV3FlashCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "weth", data: BytesLike): Result;

  events: {
    "Migrated(address,tuple,tuple,uint256,uint256)": EventFragment;
    "Sweep(address,address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Migrated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Sweep"): EventFragment;
}

export interface MigratedEventObject {
  user: string;
  compoundV2Position: CometMigratorV2.CompoundV2PositionStructOutput;
  aaveV2Position: CometMigratorV2.AaveV2PositionStructOutput;
  flashAmount: BigNumber;
  flashAmountWithFee: BigNumber;
}
export type MigratedEvent = TypedEvent<
  [
    string,
    CometMigratorV2.CompoundV2PositionStructOutput,
    CometMigratorV2.AaveV2PositionStructOutput,
    BigNumber,
    BigNumber
  ],
  MigratedEventObject
>;

export type MigratedEventFilter = TypedEventFilter<MigratedEvent>;

export interface SweepEventObject {
  sweeper: string;
  recipient: string;
  asset: string;
  amount: BigNumber;
}
export type SweepEvent = TypedEvent<
  [string, string, string, BigNumber],
  SweepEventObject
>;

export type SweepEventFilter = TypedEventFilter<SweepEvent>;

export interface CometMigratorV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CometMigratorV2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    aaveV2LendingPool(overrides?: CallOverrides): Promise<[string]>;

    baseToken(overrides?: CallOverrides): Promise<[string]>;

    cETH(overrides?: CallOverrides): Promise<[string]>;

    comet(overrides?: CallOverrides): Promise<[string]>;

    inMigration(overrides?: CallOverrides): Promise<[BigNumber]>;

    isUniswapLiquidityPoolToken0(overrides?: CallOverrides): Promise<[boolean]>;

    migrate(
      compoundV2Position: CometMigratorV2.CompoundV2PositionStruct,
      aaveV2Position: CometMigratorV2.AaveV2PositionStruct,
      flashAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapRouter(overrides?: CallOverrides): Promise<[string]>;

    sweep(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sweepee(overrides?: CallOverrides): Promise<[string]>;

    uniswapLiquidityPool(overrides?: CallOverrides): Promise<[string]>;

    uniswapV3FlashCallback(
      fee0: PromiseOrValue<BigNumberish>,
      fee1: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    weth(overrides?: CallOverrides): Promise<[string]>;
  };

  aaveV2LendingPool(overrides?: CallOverrides): Promise<string>;

  baseToken(overrides?: CallOverrides): Promise<string>;

  cETH(overrides?: CallOverrides): Promise<string>;

  comet(overrides?: CallOverrides): Promise<string>;

  inMigration(overrides?: CallOverrides): Promise<BigNumber>;

  isUniswapLiquidityPoolToken0(overrides?: CallOverrides): Promise<boolean>;

  migrate(
    compoundV2Position: CometMigratorV2.CompoundV2PositionStruct,
    aaveV2Position: CometMigratorV2.AaveV2PositionStruct,
    flashAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapRouter(overrides?: CallOverrides): Promise<string>;

  sweep(
    token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sweepee(overrides?: CallOverrides): Promise<string>;

  uniswapLiquidityPool(overrides?: CallOverrides): Promise<string>;

  uniswapV3FlashCallback(
    fee0: PromiseOrValue<BigNumberish>,
    fee1: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  weth(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    aaveV2LendingPool(overrides?: CallOverrides): Promise<string>;

    baseToken(overrides?: CallOverrides): Promise<string>;

    cETH(overrides?: CallOverrides): Promise<string>;

    comet(overrides?: CallOverrides): Promise<string>;

    inMigration(overrides?: CallOverrides): Promise<BigNumber>;

    isUniswapLiquidityPoolToken0(overrides?: CallOverrides): Promise<boolean>;

    migrate(
      compoundV2Position: CometMigratorV2.CompoundV2PositionStruct,
      aaveV2Position: CometMigratorV2.AaveV2PositionStruct,
      flashAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    swapRouter(overrides?: CallOverrides): Promise<string>;

    sweep(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    sweepee(overrides?: CallOverrides): Promise<string>;

    uniswapLiquidityPool(overrides?: CallOverrides): Promise<string>;

    uniswapV3FlashCallback(
      fee0: PromiseOrValue<BigNumberish>,
      fee1: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    weth(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "Migrated(address,tuple,tuple,uint256,uint256)"(
      user?: PromiseOrValue<string> | null,
      compoundV2Position?: null,
      aaveV2Position?: null,
      flashAmount?: null,
      flashAmountWithFee?: null
    ): MigratedEventFilter;
    Migrated(
      user?: PromiseOrValue<string> | null,
      compoundV2Position?: null,
      aaveV2Position?: null,
      flashAmount?: null,
      flashAmountWithFee?: null
    ): MigratedEventFilter;

    "Sweep(address,address,address,uint256)"(
      sweeper?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      asset?: PromiseOrValue<string> | null,
      amount?: null
    ): SweepEventFilter;
    Sweep(
      sweeper?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      asset?: PromiseOrValue<string> | null,
      amount?: null
    ): SweepEventFilter;
  };

  estimateGas: {
    aaveV2LendingPool(overrides?: CallOverrides): Promise<BigNumber>;

    baseToken(overrides?: CallOverrides): Promise<BigNumber>;

    cETH(overrides?: CallOverrides): Promise<BigNumber>;

    comet(overrides?: CallOverrides): Promise<BigNumber>;

    inMigration(overrides?: CallOverrides): Promise<BigNumber>;

    isUniswapLiquidityPoolToken0(overrides?: CallOverrides): Promise<BigNumber>;

    migrate(
      compoundV2Position: CometMigratorV2.CompoundV2PositionStruct,
      aaveV2Position: CometMigratorV2.AaveV2PositionStruct,
      flashAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapRouter(overrides?: CallOverrides): Promise<BigNumber>;

    sweep(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sweepee(overrides?: CallOverrides): Promise<BigNumber>;

    uniswapLiquidityPool(overrides?: CallOverrides): Promise<BigNumber>;

    uniswapV3FlashCallback(
      fee0: PromiseOrValue<BigNumberish>,
      fee1: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    weth(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    aaveV2LendingPool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    baseToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    comet(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    inMigration(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isUniswapLiquidityPoolToken0(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    migrate(
      compoundV2Position: CometMigratorV2.CompoundV2PositionStruct,
      aaveV2Position: CometMigratorV2.AaveV2PositionStruct,
      flashAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sweep(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sweepee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    uniswapLiquidityPool(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    uniswapV3FlashCallback(
      fee0: PromiseOrValue<BigNumberish>,
      fee1: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    weth(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
